export type PublicPolicy = Readonly<{
  slug: string;
  key: "terms" | "privacy" | "refund" | "ai_disclosure" | "leaderboard_sharing" | "fair_use";
  version: string;
  title: string;
  summary: string;
  sections: readonly Readonly<{ heading: string; body: readonly string[] }>[];
}>;

export const publicPolicies: readonly PublicPolicy[] = [
  {
    slug: "terms",
    key: "terms",
    version: "2026-09-03",
    title: "SkillUp Terms of Use",
    summary:
      "These launch terms explain acceptable use, account responsibilities, learning-content limits and service availability.",
    sections: [
      {
        heading: "Use SkillUp responsibly",
        body: [
          "Use SkillUp lawfully, keep your account and verification codes secure, and do not share sessions with another person.",
          "Do not disrupt the service, scrape unpublished content, manipulate scores, evade mission or payment controls, or attempt unauthorized security testing.",
        ],
      },
      {
        heading: "Learning-content boundary",
        body: [
          "SkillUp provides educational practice and guidance. It is not professional certification, guaranteed employment advice, or a promise of income or fluency.",
          "Published content is versioned and reviewed, but learners should still apply judgment and verify material where decisions carry material risk.",
        ],
      },
      {
        heading: "Availability and enforcement",
        body: [
          "SkillUp may limit, suspend or revoke access to protect learners, payments, content quality and platform security.",
          "Material policy updates are published as a new version and may require a fresh acknowledgement.",
        ],
      },
    ],
  },
  {
    slug: "privacy",
    key: "privacy",
    version: "2026-09-03",
    title: "SkillUp Privacy Notice",
    summary:
      "This notice explains what learner information SkillUp uses, why it is needed and which controls are available.",
    sections: [
      {
        heading: "Information required to operate SkillUp",
        body: [
          "SkillUp uses minimized account, session, profile, learning, security, support and commercial records to provide the service and protect its integrity.",
          "Authentication codes, session secrets, payment credentials and protected answer logic are never used for advertising.",
        ],
      },
      {
        heading: "Optional analytics and sharing",
        body: [
          "Product analytics, marketing contact, leaderboard aliases, achievement sharing and AI-assisted personalization are controlled independently from the account page.",
          "Authoritative payment, entitlement, score and publication outcomes are generated by the server and cannot be replaced by client analytics events.",
        ],
      },
      {
        heading: "Export, deletion and retention",
        body: [
          "Learners can inspect sessions, revoke access, download a bounded data export and schedule account deletion with a seven-day cooldown.",
          "Required payment, fraud-prevention, legal and privileged audit records may remain after personal profile data is deleted or pseudonymized.",
        ],
      },
    ],
  },
  {
    slug: "refund",
    key: "refund",
    version: "2026-09-03",
    title: "SkillUp Refund and Cancellation Policy",
    summary:
      "This policy describes manual renewal, payment review, refunds and the effect of a refund on premium access.",
    sections: [
      {
        heading: "Manual renewal and cancellation",
        body: [
          "Launch plans use manual renewal unless recurring payment is separately approved and clearly disclosed in a later policy version.",
          "An expiring plan does not automatically charge the learner under the current launch policy. To stop using Premium, no recurring cancellation action is required under manual renewal; access returns to the free plan at expiry.",
        ],
      },
      {
        heading: "Payment and refund review",
        body: [
          "Payment disputes and refund requests are reviewed against both JazzCash evidence and SkillUp's authoritative order, payment-event and entitlement records.",
          "To request a payment or refund review, use the SkillUp support page and include the SkillUp merchant reference and provider reference shown in your private payment history. Never send a JazzCash PIN, one-time code, password or full payment credential.",
          "Provider processing and settlement timing can affect when an approved refund appears.",
        ],
      },
      {
        heading: "Effect on premium access and learning history",
        body: [
          "An approved refund revokes future premium capabilities without deleting completed learning history, earned evidence or required transaction audit records.",
        ],
      },
    ],
  },
  {
    slug: "ai-disclosure",
    key: "ai_disclosure",
    version: "2026-09-03",
    title: "SkillUp AI Use Disclosure",
    summary:
      "This disclosure explains where approved AI models may assist and which human-review, privacy and authority boundaries apply.",
    sections: [
      {
        heading: "Approved uses",
        body: [
          "AI may assist with drafts, explanations, translations, quality review and recommendations through versioned task contracts and strict cost limits.",
          "Public or learner-facing generated content must pass validation and the approved human publication workflow.",
        ],
      },
      {
        heading: "What AI cannot control",
        body: [
          "Model output cannot grant premium access, change authoritative payments, override prerequisites, create administrative privilege or silently rewrite learner scores.",
          "Deterministic rules remain available when the provider is disabled, unavailable or below confidence thresholds.",
        ],
      },
      {
        heading: "Learner safety",
        body: [
          "Do not submit passwords, verification codes, financial credentials, medical details or other highly sensitive information to AI-assisted features.",
          "Short responses use explicit uncertainty and manual-review fallback until an approved rubric and live model evaluation are enabled.",
        ],
      },
    ],
  },
  {
    slug: "sharing",
    key: "leaderboard_sharing",
    version: "2026-09-03",
    title: "Leaderboard and Achievement Sharing",
    summary:
      "Sharing is optional and uses approved public aliases and achievement information rather than private account details.",
    sections: [
      {
        heading: "Private by default",
        body: [
          "Leaderboard and achievement sharing remain disabled unless the learner enables them.",
          "Email, age, authentication data, private responses, learning history and payment information are not included in public sharing.",
        ],
      },
      {
        heading: "Moderation and corrections",
        body: [
          "SkillUp may moderate abusive aliases, misleading share cards or manipulated activity while preserving append-only evidence of decisions and reward corrections.",
        ],
      },
    ],
  },
  {
    slug: "fair-use",
    key: "fair_use",
    version: "2026-09-03",
    title: "SkillUp Fair Use Policy",
    summary:
      "This policy protects learning quality and service availability by limiting automation, manipulation and attempts to bypass controls.",
    sections: [
      {
        heading: "Prohibited activity",
        body: [
          "Do not automate excessive requests, scrape unpublished content, share authentication sessions, replay payment callbacks, manipulate points or evade mission limits.",
          "Do not use SkillUp to create harmful or unlawful material or to probe systems without written authorization and a bounded scope.",
        ],
      },
      {
        heading: "Controls and enforcement",
        body: [
          "Rate limits, provider budgets, capability checks and abuse controls apply to both browser and internal API access.",
          "SkillUp may suspend affected functionality or accounts while investigating security, payment or platform-integrity risks.",
        ],
      },
    ],
  },
] as const;

export function publicPolicy(slug: string): PublicPolicy | null {
  return publicPolicies.find((policy) => policy.slug === slug) ?? null;
}
